# Charroulette Balatro Mod
# Lovely inyections
# lu1smgb@18/12/2024
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Replaces splash Joker with Hello World Joker
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_joker'])"
position = 'after'
match_indent = true
payload = '''
SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_chr_helloworld'])
'''

# Replaces Ace of Spades from menu with Hello World Joker
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.S_A, G.P_CENTERS.c_base)"
position = 'at'
match_indent = true
payload = '''
local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.empty, G.P_CENTERS['j_chr_helloworld'])
'''